### PR TITLE
[OK TO MERGE] both widgets rendering , init mapbox and gpx rendering for…

### PR DESCRIPTION
**Pull request by cjm771**
@ryanbrennan12 - Primary
@MengRS - Secondary

Added better widget placeholders (just using trail_id 1 right now) and other things:

 - cors
 - mapbox rendering gpx (path widget)
 - basic list for recordings

Please confirm, this renders for you :D. layout should be same as whats in shared folder

should look like:

image

### CODE REVIEW

**Comment by rybrennan** [comment]
got it. thx chris

**Comment by rybrennan** [comment]
path widget and recordings rendered for trail_id 1. I'll reach out to Meng to confirm as well for merge;)

**Comment by MengRS** [comment]
both widgets rendered properly on my machine... 

btw - @cjm771 - are your jest tests suppose to pass at this moment?

**Comment by cjm771** [comment]
@MengRS yes shoulllddd be, but looks like i was missing some declarations . fixed now. lemee know if they failing still.

**Comment by cjm771** [comment]
cool if this is good please merge at leisure @MengRS @ryanbrennan12

**Pull request merged**
