### PR TITLE
[Ready for Review] Proxy and services set up for own widgets

### PR DESCRIPTION
**Pull request by cjm771**
Need to confirm proxy server is inserting into dom appropriately! I basically copied  the scaffold from ./proxy-reference-files/shared/ (and also have a npm script that does this).

 You can see my methodology here: https://github.com/rpt09-scully/paths-service/tree/02_react_basic_app#158-proxy-service-launcher--inserting-into-it-dom

``` sh
# clone my proxy server 
$> git clone https://github.com/rpt09-scully/chris-proxy-service.git
# npm install dependencies
$> cd chris-proxy-service/
$> npm install
# launch services + proxy (opt, you can do this manually)
$> killall -9 node 
$> ./proxy-reference-files/shared/launch/launch.sh
```

then go to `localhost:3000`... it should look like this:

image

### CODE REVIEW

**Comment by McCloudFace** [comment]
@cjm771 - service launcher is super cool, well done. This PR seems totally straightforward.
* Ran your component-only view at http://localhost:3005, functioning as-expected.
* Ran `launch.sh` and proxy runs and displays your component for path widget. Don't see the recordings widget yet tho. Is that expected at this point in the branch?

**Comment by cjm771** [comment]
@McCloudFace hmm so it doesnt look like the screenshot? Just placeholders as shown (literally that text) should be seen, Im going to flesh out the actual widgets next! If you dont see the <h2>Recordings Widget</h2> In the proxy let me know!

**Comment by McCloudFace** [comment]
@cjm771 - Wait, you hide something behind a tab and expect me to FIND IT? 😱
My bad, it's there.  Also, love the auto-name-spaced-id-loop-that-renders bit in the shared layout. That is 💰

**Comment by cjm771** [comment]
oh haha yeah forgot to add that tidbit about tabs heh. that makes me think we might need to hire a ux designer. k cool! All is good, then merge this puppy

**Comment by cjm771** [comment]
Yeah that makes sense because all the paths service has the app.js so if it’s not running the same time as proxy, it won’t grab that file

Kind Regards,
Chris Malcolm

**Pull request merged**
